config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :sessions
  resources :languages

  root 'application#index'

end

app/models/language.rb
class Language < ActiveRecord::Base

  validates :name, uniqueness: true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def index
    
  end
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController

  def index
    @languages = Language.all
  end

  def new
    @language = Language.new
  end

  def create
    @language = Language.new(language_params)

    if @language.save
      redirect_to languages_path
    else
      render 'new'
    end
  end

  def show
    @languages = Language.all
  end

  private
  def language_params
    params.require(:language).permit(:name)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(:username => params[:session][:username])
    if (@user && @user.password == params[:password])
      auth_login(@user)
      redirect_to @user
    end
  end

  def destroy
    session.destroy
    render 'index'
  end

  private
    def auth_login(user)
      session[:user_id] = user.id
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(session[:user_id])
    @user
  end



  private
    def user_params
      params.require(:user).permit(:first_name, :last_name, :username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def auth_logged_in?
    !session[:user_id].nil?
  end

  def auth_login(user)
    session[:user_id] = user.id
  end

  def auth_logout
    session.destroy
  end

  def auth_current_user
    return nil unless session[:user_id]
    @current_user ||= User.find(session[:user_id])
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/index.html.erb
Always Monkies. Always.

app/views/languages/index.html.erb
<h1>All Languages</h1>

<% if auth_logged_in? %>
  <div class="row">
    <a id="new-language-button" class="btn" href="/languages/new">Add a Language<a/>
  </div>
  <!-- Hidden form div for AJAX magic -->
  <div id="new-language-form-container" class="col s12" style="display: none;"></div>

<% end %>
<div id="languages">
  <% if @languages %>
    <% @languages.each do |language| %>
      <div class="col s6 m3">
        <div class="card small">
          <div class="card-image lang-image">
           <h1 class="circle lang-code"><%= language.code %></h1>
          </div>
          <div class="card-content lang-name">
            <h4><%= language.name %></h4>
            
          </div>
          <div class="card-action">
            <a href="/languages/<%= language.id %>">Details</a>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/languages/new.html.erb
<%= form_for :language, url: languages_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LanguagePair</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <!-- <link rel="stylesheet" type="text/css" href="/app/assets/stylesheets/materialize.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.0/js/materialize.min.js"></script> -->
</head>
<body>
  <nav id="navbar">
      <div class="nav-wrapper">
        <a href="/" class="brand-logo hide-on-med-and-down">Language Pair</a>
        <ul id="nav-mobile" class="right">
          <li><%= link_to 'All Languages', languages_path %></li>
          <li><a href="/about">About</a></li>
          <% if auth_logged_in? %>
            <li><a href="/profile">Profile</a></li>
            <li><%= link_to 'Log Out', session_path(session), method: :delete %></li>
          <% else %>
            <li><%= link_to 'Log In', new_session_path %></li>
            <li><%= link_to 'Register', new_user_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <div class="container center">
      <%= yield %>
    </div>
    <footer class="page-footer" id="foot">
      <div class="footer-copyright" id="foot">
        <div class="container copyright-footer center" id="foot">
          <b>© 2015 Copyright &nbsp;<a class="grey-text text-lighten-4" href="https://github.com/jbomotti" target="_blank">James Bomotti</a></b>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/new.html.erb
<h1>Register</h1>
<%= form_for :user, url: users_path do |f| %>
  <p>
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </p>

  <p>
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </p>

  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>

  <p>
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </p>

  <p>
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/users/show.html.erb
<%= @user.username %>

<%= auth_current_user.username %>